{{- if .Values.orderService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: order-service
  ports:
  - port: {{ .Values.orderService.service.port }}
    targetPort: 3002
{{- end }}
