{{- if .Values.userService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: user-service
  ports:
  - port: {{ .Values.userService.service.port }}
    targetPort: 3001
{{- end }}
